name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (Python)
        run: |
          pytest --maxfail=1 --disable-warnings -v

      - name: Install dependencies (Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm install
          npm run test

      # Add more steps for HTML/Shell as needed here

      - name: Build project
        run: |
          # Example build step (customize as needed)
          mkdir -p dist
          echo "Build output here" > dist/index.html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Example deploy step (customize to your needs)
      - name: Deploy to server
        run: echo "Deploying..."

      # Optionally add more deployment actions
